#include "core_config.h"
#include "console.h"
#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void coreConfigInit(coreConfig_t *cfg)
{
	memset(cfg, 0, sizeof(*cfg));
	cfg->vars = NULL;
}

void coreConfigShutdown(coreConfig_t *cfg)
{
	cfgVar_t *v = cfg->vars;
	while (v) {
		cfgVar_t *next = v->next;
		free(v->stringVal);
		free(v);
		v = next;
	}
	cfg->vars = NULL;
}

static cfgVar_t *configFindOrCreate(coreConfig_t *cfg, const char *name)
{
	cfgVar_t *v;
	for (v = cfg->vars; v; v = v->next) {
		if (_stricmp(v->name, name) == 0)
			return v;
	}
	v = calloc(1, sizeof(cfgVar_t));
	strncpy(v->name, name, sizeof(v->name) - 1);
	v->name[sizeof(v->name) - 1] = '\0';
	v->stringVal = AllocString("");
	v->flags = CFG_NONE;
	v->next = cfg->vars;
	cfg->vars = v;
	return v;
}

static const char *skipWhitespace(const char *s)
{
	while (*s == ' ' || *s == '\t')
		s++;
	return s;
}

static const char *readQuoted(const char *s, char *out, int maxLen)
{
	if (*s == '"') {
		s++;
		int i = 0;
		while (*s && *s != '"' && i < maxLen - 1) {
			out[i++] = *s++;
		}
		out[i] = '\0';
		if (*s == '"')
			s++;
	} else {
		int i = 0;
		while (*s && *s != ' ' && *s != '\t' && *s != '\n' && *s != '\r' && i < maxLen - 1) {
			out[i++] = *s++;
		}
		out[i] = '\0';
	}
	return s;
}

int coreConfigLoad(coreConfig_t *cfg, const char *path)
{
	FILE *f = fopen(path, "r");
	if (!f)
		return 0;

	char line[2048];
	while (fgets(line, sizeof(line), f)) {
		const char *s = skipWhitespace(line);

		if (*s == '\0' || *s == '\n' || *s == '\r' || *s == '/' || *s == '#')
			continue;

		if (_strnicmp(s, "set ", 4) != 0)
			continue;

		s = skipWhitespace(s + 4);

		char key[256];
		s = readQuoted(s, key, sizeof(key));
		if (key[0] == '\0')
			continue;

		s = skipWhitespace(s);

		char val[1024];
		s = readQuoted(s, val, sizeof(val));

		cfgVar_t *v = configFindOrCreate(cfg, key);
		FreeString(v->stringVal);
		v->stringVal = AllocString(val);
	}

	fclose(f);
	return 1;
}

int coreConfigSave(coreConfig_t *cfg, const char *path)
{
	FILE *f = fopen(path, "w");
	if (!f)
		return 0;

	fprintf(f, "// Generated by " CFG_VERSION "\n");

	cfgVar_t *v;
	for (v = cfg->vars; v; v = v->next) {
		if (!(v->flags & CFG_ARCHIVE))
			continue;
		fprintf(f, "set \"%s\" \"%s\"\n", v->name, v->stringVal);
	}

	fclose(f);
	return 1;
}

cfgVar_t *coreConfigFind(coreConfig_t *cfg, const char *name)
{
	cfgVar_t *v;
	for (v = cfg->vars; v; v = v->next) {
		if (_stricmp(v->name, name) == 0)
			return v;
	}
	return NULL;
}

void coreConfigSetString(coreConfig_t *cfg, const char *name, const char *value)
{
	cfgVar_t *v = configFindOrCreate(cfg, name);
	FreeString(v->stringVal);
	v->stringVal = AllocString(value);

	conVar_t *cv = conCvar_Find(name);
	if (cv)
		conCvar_Set(name, value);
}

int coreConfigGetInt(coreConfig_t *cfg, const char *name, int def)
{
	cfgVar_t *v = coreConfigFind(cfg, name);
	if (!v || !v->stringVal || v->stringVal[0] == '\0')
		return def;
	return atoi(v->stringVal);
}

float coreConfigGetFloat(coreConfig_t *cfg, const char *name, float def)
{
	cfgVar_t *v = coreConfigFind(cfg, name);
	if (!v || !v->stringVal || v->stringVal[0] == '\0')
		return def;
	return (float)atof(v->stringVal);
}

int coreConfigGetBool(coreConfig_t *cfg, const char *name, int def)
{
	cfgVar_t *v = coreConfigFind(cfg, name);
	if (!v || !v->stringVal || v->stringVal[0] == '\0')
		return def;
	if (_stricmp(v->stringVal, "true") == 0 || _stricmp(v->stringVal, "1") == 0 ||
		_stricmp(v->stringVal, "yes") == 0 || _stricmp(v->stringVal, "on") == 0)
		return 1;
	if (_stricmp(v->stringVal, "false") == 0 || _stricmp(v->stringVal, "0") == 0 ||
		_stricmp(v->stringVal, "no") == 0 || _stricmp(v->stringVal, "off") == 0)
		return 0;
	return def;
}
